### ISSUE TITLE
Implement a unified ingest pipeline (sup)

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-app#710]
- [ ] https://github.com/monarch-initiative/monarch-app/issues/707
- [ ] https://github.com/monarch-initiative/monarch-app/issues/709
- [ ] https://github.com/monarch-initiative/monarch-app/issues/708

--------------
<img width="1302" alt="Screen Shot 2024-05-22 at 10 19 23 AM" src="https://github.com/monarch-initiative/monarch-app/assets/1714621/a2508ac6-7dd3-401b-b303-2bccba63e327">

**Comment by sagehrke** [comment]
@madanucd Please do the following: 

> _Create examples of G2D associations that are (1) common between files and (2) examples where they are in one file but not the other. Do this generally across the files, but also with a specific focus on a comparison of the files to HPOA. A handful of examples should be good (maybe up to 20)._

**Comment by madanucd** [comment]
Hi @sagehrke,

As discussed earlier, I've analyzed the five data sources that provide gene-to-disease (G2D) associations and have generated a set of assets based on this analysis. These assets have been released here: [AUG 2024 Release](https://github.com/monarch-initiative/source-data-analysis/releases/tag/2024-08-13).

Below are the details of the requested associations:

- G2D associations common across different sources/files: In the release assets, you can find a spreadsheet titled `g2d_consolidated_edges.xlsx`. This file contains three columns: `disease_id`, `gene_id`, and `sources`, where the `sources` column lists the contributing sources in a pipe-delimited format. By filtering for all sources, you can identify the G2D associations common across all sources.

- G2D associations present in one file but missing in others: The release also includes a spreadsheet named `g2d_unique_edges.xlsx`, which highlights G2D associations that appear in only one source and are absent in others. This file is organized into separate tabs for each source, making it easy to pinpoint unique associations.

Additionally, the release contains various visualizations and other artifacts. For more details, please refer to the documentation here: [G2D Analysis Documentation](https://monarch-initiative.github.io/source-data-analysis/g2d/).

Please let me know if there is anything else you need!

**Comment by sagehrke** [comment]
@cmungall Can you give more direction on what is needed, if anything, to finish up this task? Thanks!
