### ISSUE TITLE
Implement modular ingests (sup)

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#714]
## Super Ticket for tracking the implementation of modular ingests

**Look here for detailed tracker -->  [Modular Ingest Tracking Table 2025 Google Sheet](https://docs.google.com/spreadsheets/d/1q_QVXAmsB8aTfNXFNleGKhBn77Oj9nVzOrNQAWNrRhU/edit?gid=0#gid=0)**
_______________

**In progress**
- [ ] https://github.com/monarch-initiative/monarch-app/issues/974
- [x] https://github.com/monarch-initiative/monarch-app/issues/946
- [ ] https://github.com/monarch-initiative/monarch-app/issues/770

**Needed**
- [ ] Documentation cleanup https://github.com/monarch-initiative/monarch-ingest/issues/622

## Notes
- Need to identify QC & reporting strategy for modular ingests. 
- Need to identify next batch of modular ingests. 
     - Tech Support for next batch: @kevinschaper @AO33 @ptgolden

**Comment by sagehrke** [comment]
@ptgolden Just a kind reminder that you said you would convert our modularization task into a table we can easily see status. Note, that you can do that here in markdown or if we want to use a google sheet, that would be fine too. Let me know if you need any support and thank you!!!

**Comment by ptgolden** [comment]
GitHub Flavored Markdown doesn't allow creating interactive checkboxes (aka "task lists") within tables, unfortunately.

Two options. First, I could make a Google Sheet.

Second, we can manually add checkmarks into a table, e.g.

|ingest key|download yaml|transform python|transform yaml|tests|documentation|import into monarch ingest|remove code from monarch ingest|
|-|-|-|-|-|-|-|-|
|alliance_genotype|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_large_square:|
|alliance_phenotype|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_large_square:|

...which would require manually editing the markdown for the table.

I'd tend towards the latter, just to keep everything in the same place, but editing the markdown by hand is a bit of a pain while working on an ingest may be a bit of a pain.

**Comment by sagehrke** [comment]
Let's go with a document so it's easier to make notes and updates. 

[Modular Ingest Tracking 2025](https://docs.google.com/spreadsheets/d/1q_QVXAmsB8aTfNXFNleGKhBn77Oj9nVzOrNQAWNrRhU/edit?gid=0#gid=0)

**Comment by sagehrke** [comment]
this is done! yay!
