### ISSUE TITLE
Add Genotype to Phenotype to Monarch-KG/app (sup)

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#715]
### Genotype ingests
 - [x] Alliance Genotype Ingest [698](https://github.com/monarch-initiative/monarch-app/issues/698)
 - [ ] Confirm that all IMPC models are in Alliance Genotype files (accounting for release cycles) [771](https://github.com/monarch-initiative/monarch-app/issues/771)

### Phenotype ingests
- [x] Alliance phenotype association ingest [700](https://github.com/monarch-initiative/monarch-app/issues/700)
- [x] ZFIN genotype to phenotype ingest [702](https://github.com/monarch-initiative/monarch-app/issues/702)

### Allele ingests
- [ ] Ingest Alleles from Alliance Variant-Allele file https://github.com/monarch-initiative/monarch-app/issues/946

### Variant ingests
- [ ] #770
- [x] Clingen [739](https://github.com/monarch-initiative/monarch-app/issues/739)
- [x] Clinvar [738](https://github.com/monarch-initiative/monarch-app/issues/738)

### Data modeling
- [ ] Add biolink predicates to support allele to genotype

### API/UI Support
- [x] Support genotype names in search and node page
- [x] Show genotype to phenotype associations in associations section
- [ ] Show allele to gene associations (May need an ingest for this?)
- [ ] Show allele to genotype associations
- [ ] Show gene to genotype associations?  (do we need to ingest or infer these?)

### Data Export
- [x] Produce tsv export files for genotype associations

### Semsimian

- [ ] Support searching for disease models in Semsimian / Phenotype Explorer

### Exomiser?
- [ ] Look at whether Exomiser can import genotypes from monarch-kg

**Comment by sagehrke** [comment]
@kevinschaper and @cmungall Can you please review this super ticket and help prioritize what is needed to finish this up? I added the https://github.com/monarch-initiative/monarch-app/issues/946 ticket as I believe it is related. Feel free to edit the first comment above for simplicity. Thanks!
