### ISSUE TITLE
Update personnel & institutions on https://monarchinitiative.org/team

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#728]
Hi @glass-ships - can you help with the following updates to the https://monarchinitiative.org/team page? 

- [x] Move everyone under CU (**exceptions below**) to a new heading for UNC. Include the UNC logo. 
   - [x] KEEP the following people under CU (and in this order): Moni, Katie, Katherina, Madan, Megan    
   - [x] ADD Daniel under new UNC heading (alphabetical order after Melissa, Julie & I) https://github.com/monarch-initiative/monarch-app/issues/727
   - [x] ADD Aaron under new UNC heading (alphabetical order after Melissa, Julie & I) #729 
   - [x] ADD photo for Katherina
   - [x] ADD photo for Trish
- [x] Move to alumni members: Faisal, Vince
- [x] Move Peter to a new heading for Charite. Include a Charite Logo. Keep everyone else listed under JAX as is. 
   - [x] ADD Leonardo under the new Charite heading (after Peter) https://github.com/monarch-initiative/monarch-app/issues/719

Confidence check: once the updates are done above, confirm the new order the institutions show up on the page are:
UNC
CU
LBL
Charite
JAX
EMBL-EBI
QMUL
JHU
Consultants
C-path
RENCI
SAB
Alumni members
Alumni groups

Please reach out with any questions. And you can tag me in the PR review. If this can be completed in the next release, that would be great, otherwise, pushing it to July would be just fine. Thank you! 
 
FYI @monicacecilia @nlharris

**Comment by sagehrke** [comment]
Note: if you have energy to put towards this, there are other folks listed that are still missing photos. You can try to chase those down and add them in this PR as well, but don't let that block the work this time around.

**Comment by glass-ships** [comment]
---
## Info Missing from Monarch UI Teams Page

If you are missing or need to update any of the information below,  
please reach out via this issue, Slack, or [email](mailto:contact@glass-ships.com) so we can get you accurately represented on the website. 

## Links

Please provide me with a link to an online profile you wish to link to from the Monarch website.  
If you are missing a link and do not wish to provide one, we can default to using your GitHub profile (if known/available). 

Missing Links:
- [x] Ben Coleman
- [ ] Martha Beckwith
- [ ] Lauren Rekerle
- [ ] Carlo Kroll

Using GitHub, let me know if you'd like another link:
- [x] @LCCarmody 
- [ ] @kcortes133 
- [ ] @turbomam 
- [ ] @twhetzel 
- [ ] @tudorgroza 

## Job Title/Position

Your role or job title within Monarch

Missing title/position:
- [ ] Ben Coleman
- [ ] Martha Beckwith
- [ ] Leonardo Chimirri
- [ ] Chris Chute
- [ ] @tudorgroza 

## Photos

The photo you would like to appear on https://monarchinitiative.org/team. 

### Guidelines for good photo:

- High res, at least 300x300 (natively, non-upscaled).
- Square, tight crop (but without cutting off face).
- Face mostly centered.
- Well-lit, good contrast.
- Minimal background distraction. Depth-of-field blur on background ideal.

### Missing photos:
- [x] Ben Coleman
- [ ] Carlo Kroll 
- [ ] Leonardo Chimirri
- [ ] Martha Beckwith 

### Could use better photo:
- [ ] James McLaughlin

**Comment by sagehrke** [comment]
@glass-ships A minor update from the initial list of to-do's: Please list Peter first under both Charite and Jax. The correct link to use for Charite is https://www.bihealth.org/en/

**Comment by glass-ships** [comment]
Thanks @sagehrke 
Apart from my above comment, I've made the requested changes in 
https://github.com/monarch-initiative/monarch-app/pull/730
Please review and let me know if there's anything additional you'd like to see before I merge it

**Comment by LCCarmody** [comment]
I'm fine with just Github link (@LCCarmody ). But note, Ben Coleman and Hannah Blau are no longer in Peter's lab/Jackson Labs. I am not sure if you have an alumni section, but they belong to that.
Daniel Danis is no longer at Jackson Labs, but he is in Peter's lab at Charite.  I am not sure if someone else from Peter's lab at Charite besides Leonardo should also be listed.
