### ISSUE TITLE
Upgrade the Monarch UI (super ticket)

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#737]
### Super ticket for upgrades to the Monarch UI
**These upgrades are at the direction of the Monarch Directors** @monarch-initiative/leadership 

### SEE PROJECT BOARD TRACKER FOR LATEST INFORMATION: https://github.com/orgs/monarch-initiative/projects/111

________

**Need Director Decision**

- [x] https://github.com/monarch-initiative/monarch-app/issues/776

 **NEW Monarch Initiative Consortium Website**
- [x] https://github.com/monarch-initiative/monarch-app/issues/774
- [x] https://github.com/monarch-initiative/monarch-app/issues/780
- [ ] https://github.com/monarch-initiative/monarch-app/issues/736
- [ ] #822
- [ ] https://github.com/monarch-initiative/monarch-app/issues/876

**Monarch KG Site**
- [x] https://github.com/monarch-initiative/monarch-app/issues/769
- [ ] https://github.com/monarch-initiative/phenomics-assistant/issues/11
- [ ] https://github.com/monarch-initiative/monarch-app/issues/337

_____
**Current work** 

- [ ] https://github.com/monarch-initiative/monarch-app/issues/750
- [ ] #887 
- [x] #951 
- [x] #744 
- [x] #949 

**Up Next**
**NEW Monarch Initiative Consortium Website**  

- [x] #932 
- [x] https://github.com/monarch-initiative/monarch-app/issues/779
- [x] https://github.com/monarch-initiative/monarch-app/issues/805
- [x] https://github.com/monarch-initiative/monarch-app/issues/806
- [x] https://github.com/monarch-initiative/monarch-app/issues/817
- [x] https://github.com/monarch-initiative/monarch-app/issues/812
- [x] https://github.com/monarch-initiative/monarch-app/issues/833
- [ ] https://github.com/monarch-initiative/monarch-app/issues/874

**Monarch KG Site**
- [x] #867
- [x] https://github.com/monarch-initiative/monarch-app/issues/882
- [ ] #788 
- [ ] #790
- [ ] https://github.com/monarch-initiative/monarch-app/issues/816
- [x] https://github.com/monarch-initiative/monarch-app/issues/806
- [ ] #821 
- [ ] https://github.com/monarch-initiative/monarch-app/issues/311
- [ ] https://github.com/monarch-initiative/monarch-app/issues/834
- [ ] #864
- [ ] #865 
- [ ] #866 
- [x] #868 
- [ ] #870
- [ ] #873
- [x] https://github.com/monarch-initiative/monarch-app/issues/875
- [ ] https://github.com/monarch-initiative/monarch-app/issues/877
- [x] https://github.com/monarch-initiative/monarch-app/issues/878
- [ ] https://github.com/monarch-initiative/monarch-app/issues/879
- [x] https://github.com/monarch-initiative/monarch-app/issues/880
- [x] https://github.com/monarch-initiative/monarch-app/issues/802

___
### Completed
- [x] #881
- [x] #872
- [x] #871
- [x] #919 
- [x] #938 
- [x] https://github.com/monarch-initiative/monarch-app/issues/881

### Completed in Sept 2024 release
- [x] https://github.com/monarch-initiative/monarch-app/issues/735 @iimpulse @amc-corey-cox 
- [x] https://github.com/monarch-initiative/monarch-app/issues/672 @kevinschaper 
- [x] https://github.com/monarch-initiative/monarch-app/issues/777 @amc-corey-cox 
- [x] https://github.com/monarch-initiative/monarch-app/issues/778 @amc-corey-cox 
- [x] https://github.com/monarch-initiative/monarch-app/issues/796

### Completed in Oct 2024 release
- [x] https://github.com/monarch-initiative/monarch-app/issues/734
- [x] https://github.com/monarch-initiative/monarch-app/pull/775
- [x] https://github.com/monarch-initiative/monarch-app/issues/828
- [x] https://github.com/monarch-initiative/monarch-app/issues/787

### Completed in Nov 2024
- [x] https://github.com/monarch-initiative/monarch-app/issues/849

**Comment by sagehrke** [comment]
I am closing this ticket. All info for the monarch UI is now on the project board linked above.
