### ISSUE TITLE
Capture feedback about proposed table with "all associations together"

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-app#849]
Following the Directors' recommendations, our Monarch Tech Team advanced a proposal to combine all the results tables into a single page, without drop-down menus, when users explore the knowledge graph with the Monarch website. It includes a navigation "column" on the left, allowing users to easily return to any sections. 

For an example of the proposed changes, please visit the Monarch development website and navigate to the Gene Page for apolipoprotein E (APOE) here: [APOE | Monarch Initiative](https://dev.monarchinitiative.org/HGNC:613). 

Please provide your feedback on this ticket. 

This ticket concerns how results are displayed and how easy it is to navigate through them. We are also working on updating some table headers (see #835 and #837); please feel free to provide additional feedback if desired. 

FYI: @kevinschaper 👀 👆🏽

**Comment by cmungall** [comment]
I **vastly** prefer this style of display. This is commonly used for all knowledge bases.

I think there are a few things that could be improved or minor bugs. I will list a few to give a flavor. But to be clear, I think this new change should go ahead, and we can incrementally improve on some aspects.

Minor:

- If there are exactly 5 associations, it allows me to advance to next to show an empty list in the range "6-5". Off by one error?
- The ordering of association on the page can be improved. Interactions is not useful and not in Monarch's core area. In contrast, diseases are. Put these before interactions
- for orthologs there may be a more intuitive column order
- it may make sense to bundle GO
- why is external info not along with the other metadata? Some seems duplicative eg. ensembl mappings
- it's clunky to say "Phenotype to Gene" and confusing since the gene is on the left. If the context/focus is already gene, then just say phenotype 
- there are many cases where you can collapse redundant annotations
- GO annotations seem to have lost their publications

**Comment by damiansm** [comment]
Some quick, general feedback

- The whole style with less white space is so much better
- I definitely prefer all the associations being shown like this - advertises what we have and much easier to find
- Do we really need the association column in every table? I guess you want to keep things generic but to me it does not add any extra useful information, is repetitive, takes up space and is a bit ontology-geeky for some general users
- Why is taxon empty in so many tables. 
- I don't get the point of the extra info section - just put all that at the top with the other xrefs.
- Breadcrumbs could be displayed in a more typical format at the top of the page?
- I would vote for a new colour scheme but sure we have another ticket for that already.

**Comment by kevinschaper** [comment]
- [ ] it's clunky to say "Phenotype to Gene" and confusing since the gene is on the left. If the context/focus is already gene, then just say phenotype https://github.com/monarch-initiative/monarch-app/issues/875
- [x] GO annotations seem to have lost their publications

**Style**
- [ ] I would vote for a new colour scheme but sure we have another ticket for that already. https://github.com/monarch-initiative/monarch-app/issues/876

**Layout/Order**
- [ ] The ordering of association on the page can be improved. Interactions is not useful and not in Monarch's core area. In contrast, diseases are. Put these before interactions https://github.com/monarch-initiative/monarch-app/issues/877
- [ ] Breadcrumbs could be displayed in a more typical format at the top of the page? https://github.com/monarch-initiative/monarch-app/issues/816
- [ ] I don't get the point of the extra info section - just put all that at the top with the other xrefs. https://github.com/monarch-initiative/monarch-app/issues/878
- [ ] why is external info not along with the other metadata? Some seems duplicative eg. ensembl mappings (duplicate of above, I think) https://github.com/monarch-initiative/monarch-app/issues/878

**Associations**

- [ ] it may make sense to bundle GO https://github.com/monarch-initiative/monarch-app/issues/879
- [ ] If there are exactly 5 associations, it allows me to advance to next to show an empty list in the range "6-5". Off by one error? https://github.com/monarch-initiative/monarch-app/issues/880
- [ ] for orthologs there may be a more intuitive column order https://github.com/monarch-initiative/monarch-app/issues/881
- [x] Why is taxon empty in so many tables.
- [ ] Do we really need the association column in every table? I guess you want to keep things generic but to me it does not add any extra useful information, is repetitive, takes up space and is a bit ontology-geeky for some general users https://github.com/monarch-initiative/monarch-app/issues/882
- [ ] there are many cases where you can collapse redundant annotations (maybe dupe of #337)

**Comment by sagehrke** [comment]
All input has been documented in individual tickets. You can see those tickets linked above and in our UI super ticket #737
